/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.alogient.aseq.mobileclaim;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int btn_flash_auto=0x7f020000;
        public static final int btn_flash_no=0x7f020001;
        public static final int btn_flash_on=0x7f020002;
        public static final int btn_flip=0x7f020003;
        public static final int btn_shot=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int screen=0x7f020006;
        public static final int viewfinder=0x7f020007;
    }
    public static final class id {
        public static final int captureButton=0x7f060003;
        public static final int flashButton=0x7f060004;
        public static final int flipCamera=0x7f060002;
        public static final int linearLayout=0x7f060001;
        public static final int preview=0x7f060000;
        public static final int viewfinder=0x7f060006;
        public static final int viewfinderArea=0x7f060005;
    }
    public static final class layout {
        public static final int nativecameraplugin=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class xml {
        public static final int config=0x7f040000;
    }
}
